### ISSUE TITLE
license issue?

### ISSUE THREAD

**Issue by KellySKwon** [hatrungduc/spark-nlp-starter-scripts#1]
Running !bash ./spark-nlp-setup-macOS-catalina.sh gave me this error:

/removed/

Is this an error with the license?

**Comment by DevinTDHa** [comment]
Hi @KellySKwon,

There was an issue with getting the OCR version, i have updated it to be more robust in the newest commit.

Please pull the latest changes, it should work by then. If there are any more persisting issues, please don't hesitate to contact Christan @C-K-Loan or me.

Best Wishes,
Devin
